export const dataNotifikasi = [
  {
    id: 1,
    title: "Website Marketplace Barang Bekas",
    category:
      "Lamaran Anda berhasil dikirim ke Founder melalui email emailfounder@gmail.com",
    desc: "Silahkan memulai diskusi via email. Status rekrutmen akan diumumkan paling lambat 15-01-2023.",
    isRead: false,
    isApproved: false,
    date: "",
  },
  {
    id: 2,
    title: "Website Marketplace Barang Bekas",
    category: "Selamat, lamaran Anda DITERIMA!",
    desc: "Aplikasi mobile untuk sistem absensi secara digital yang sangat praktis",
    isRead: true,
    isApproved: true,
    date: "",
  },
  {
    id: 3,
    title: "Website Marketplace Barang Bekas",
    category: "Mohon maaf, lamaran Anda DITOLAK",
    desc: "Tetap semangat! Upgrade profilmu dan jelajahi proyek lainnya!",
    isRead: true,
    isApproved: false,
    date: "",
  },
  {
    id: 4,
    title: "Website Marketplace Barang Bekas",
    category: "Nama Pelamar mengajukan lamaran ke proyek anda",
    desc: "Cek email dan detail proyek Anda, konfirmasi sebelum 15-01-2023.",
    isRead: true,
    isApproved: false,
    date: "",
  },
  {
    id: 5,
    title: "Website Marketplace Barang Bekas",
    category: "Nama Pelamar siap bekerja dengan anda",
    desc: "Lanjutkan diskusi melalui email untuk membahas kelanjutannya.",
    isRead: true,
    isApproved: false,
    date: "",
  },
  {
    id: 6,
    title: "Website Marketplace Barang Bekas",
    category: "Nama Pelamar membatalkan lamaran",
    desc: "Beri kesempatan pada pelamar lain untuk menggantikan.",
    isRead: true,
    isApproved: false,
    date: "",
  },
];
